services:
  app:
    image: ${DOCKER_REPO:-project-management}:app
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/.env:ro
      - storage-uploads:/var/www/storage/app/public
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-southeast-1"
        awslogs-group: "${LOG_GROUP:-/pm-app/dev}"
        awslogs-stream: "app"
        mode: "non-blocking"
        max-buffer-size: "4m"

  nginx:
    image: ${DOCKER_REPO:-project-management}:nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8088}:80"
    depends_on:
      - app
    volumes:
      - storage-uploads:/var/www/public/storage:ro
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-southeast-1"
        awslogs-group: "${LOG_GROUP:-/pm-app/dev}"
        awslogs-stream: "nginx"
        mode: "non-blocking"
        max-buffer-size: "4m"

volumes:
  storage-uploads:
