server {
    listen 80;
    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        set $forwarded_proto $http_x_forwarded_proto;
        if ($http_cloudfront_forwarded_proto = "https") {
            set $forwarded_proto "https";
        }
        if ($forwarded_proto = "") {
            set $forwarded_proto "https";
        }

        fastcgi_param HTTP_X_FORWARDED_PROTO $forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
    }
}
